# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Python-Projects/SimpleVideoGUI/SimpleVideoGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimpleVideoGUI(object):
    def setupUi(self, SimpleVideoGUI):
        SimpleVideoGUI.setObjectName("SimpleVideoGUI")
        SimpleVideoGUI.resize(800, 480)
        self.layoutWidget = QtWidgets.QWidget(SimpleVideoGUI)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 464))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currTimeLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.currTimeLabel.setFont(font)
        self.currTimeLabel.setObjectName("currTimeLabel")
        self.horizontalLayout.addWidget(self.currTimeLabel)
        spacerItem = QtWidgets.QSpacerItem(24, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.startButton.setAutoDefault(False)
        self.startButton.setDefault(False)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.restartButton = QtWidgets.QPushButton(self.layoutWidget)
        self.restartButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.restartButton.setObjectName("restartButton")
        self.horizontalLayout.addWidget(self.restartButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.currDateLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.currDateLabel.setFont(font)
        self.currDateLabel.setObjectName("currDateLabel")
        self.horizontalLayout.addWidget(self.currDateLabel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.VidFrame = QtWidgets.QWidget(self.layoutWidget)
        self.VidFrame.setMinimumSize(QtCore.QSize(640, 360))
        self.VidFrame.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(240, 240, 240)")
        self.VidFrame.setObjectName("VidFrame")
        self.horizontalLayout_2.addWidget(self.VidFrame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.redLightButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redLightButton.sizePolicy().hasHeightForWidth())
        self.redLightButton.setSizePolicy(sizePolicy)
        self.redLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.redLightButton.setObjectName("redLightButton")
        self.verticalLayout.addWidget(self.redLightButton)
        self.yellowLightButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yellowLightButton.sizePolicy().hasHeightForWidth())
        self.yellowLightButton.setSizePolicy(sizePolicy)
        self.yellowLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.yellowLightButton.setObjectName("yellowLightButton")
        self.verticalLayout.addWidget(self.yellowLightButton)
        self.greenLightButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenLightButton.sizePolicy().hasHeightForWidth())
        self.greenLightButton.setSizePolicy(sizePolicy)
        self.greenLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.greenLightButton.setObjectName("greenLightButton")
        self.verticalLayout.addWidget(self.greenLightButton)
        self.redBlinkButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redBlinkButton.sizePolicy().hasHeightForWidth())
        self.redBlinkButton.setSizePolicy(sizePolicy)
        self.redBlinkButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.redBlinkButton.setObjectName("redBlinkButton")
        self.verticalLayout.addWidget(self.redBlinkButton)
        self.yellowBlinkButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yellowBlinkButton.sizePolicy().hasHeightForWidth())
        self.yellowBlinkButton.setSizePolicy(sizePolicy)
        self.yellowBlinkButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.yellowBlinkButton.setObjectName("yellowBlinkButton")
        self.verticalLayout.addWidget(self.yellowBlinkButton)
        self.greenBlinkButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenBlinkButton.sizePolicy().hasHeightForWidth())
        self.greenBlinkButton.setSizePolicy(sizePolicy)
        self.greenBlinkButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.greenBlinkButton.setObjectName("greenBlinkButton")
        self.verticalLayout.addWidget(self.greenBlinkButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(SimpleVideoGUI)
        QtCore.QMetaObject.connectSlotsByName(SimpleVideoGUI)

    def retranslateUi(self, SimpleVideoGUI):
        _translate = QtCore.QCoreApplication.translate
        SimpleVideoGUI.setWindowTitle(_translate("SimpleVideoGUI", "Form"))
        self.currTimeLabel.setText(_translate("SimpleVideoGUI", "HH:MM:SS PM"))
        self.startButton.setText(_translate("SimpleVideoGUI", "Start Video"))
        self.restartButton.setText(_translate("SimpleVideoGUI", "Restart"))
        self.currDateLabel.setText(_translate("SimpleVideoGUI", "DD-MMM-YYYY"))
        self.redLightButton.setText(_translate("SimpleVideoGUI", "Red On"))
        self.yellowLightButton.setText(_translate("SimpleVideoGUI", "Yellow On"))
        self.greenLightButton.setText(_translate("SimpleVideoGUI", "Green On"))
        self.redBlinkButton.setText(_translate("SimpleVideoGUI", "Red Blink"))
        self.yellowBlinkButton.setText(_translate("SimpleVideoGUI", "Yellow Blink"))
        self.greenBlinkButton.setText(_translate("SimpleVideoGUI", "Green Blink"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SimpleVideoGUI = QtWidgets.QWidget()
    ui = Ui_SimpleVideoGUI()
    ui.setupUi(SimpleVideoGUI)
    SimpleVideoGUI.show()
    sys.exit(app.exec_())

